version: "3.8"

services:
  api:
    container_name: eduhub_api
    build: .
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - ${PORT}:4040
    command: sh -c "npm run db:setup && npm run start"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: eduhub_bd
    image: postgis/postgis:16-master
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
